### ISSUE TITLE
Documentation for setup is not clear

### ISSUE THREAD

**Issue by mabar** [naja-js/naja#370]
Using a bundler may be complicated for some users and pre-built version of Naja is hard to find.

Pre-built is currently mentioned in [installation](https://naja.js.org/#/installation), but not in [quick start](https://naja.js.org/#/quick-start)

Also [tutorial](https://naja.js.org/#/guide/01-install-setup-naja) could probably mention that npm and webpack are possibilities used for tutorial purposes but are not requirements.

**Comment by jiripudil** [comment]
Hi,

The tutorial already hints at alternative ways to install Naja, and links to the Installation page. But yeah, perhaps it could be worded in a more explicit fashion.

As to the quick start: while using npm and a a bundler is the preferred way of installing Naja and is becoming an industry standard, I admit the start is really only quick if you're already set up on that front. I think the quick start could be split into two sections, similarly to the Installation manual.
