### ISSUE TITLE
What is `snippet`'s type?

### ISSUE THREAD

**Issue by zipper** [naja-js/naja#379]
The `SnippetHandler.updateSnippet` declares, that it recieves `snippet` as `HTMLElement`, but the events `AfterUpdateEvent` and `BeforeUpdateEvent` then have it declared as `Element`. Based on other code occurences (`SnippetHandler.findSnippets` where snippets are retrieved, type `SnippetUpdateOperation`, ...), I guess that the Element should be right.

Shouldn't there therefore be `Element` in `updateSnippet` method signature as well?

**Comment by jiripudil** [comment]
Hi, yes, you're probably right. Could you please send a PR?
