### ISSUE TITLE
URL is not updated correctly after async redirect

### ISSUE THREAD

**Issue by jiripudil** [naja-js/naja#385]
# Bug Report

When the server responds with a redirect that Naja follows asynchronously, the location is incorrectly updated to the original request's URL. I believe the culprit is [this coalescing assignment](https://github.com/naja-js/naja/blob/384d298a9199bf778985d1bcf5747fe8de305b22/src/core/HistoryHandler.ts#L71), which preserves `href` from the first request.

To fix this, I think `HistoryHandler` could listen to the `redirect` event and update `options.href` to the redirected URL 🤔

**Comment by Ragnarrlothbrok** [comment]
Hi, I would like to contribute to this.

**Comment by JanRossler** [comment]
I can confirm that updating `options.href` during `redirect` event fixes the issue for me:
```js
        naja.redirectHandler.addEventListener('redirect', (event) => {
            event.detail.options.href = event.detail.url;
        });
```
