### ISSUE TITLE
Leverage browser cache when response ETag is set

### ISSUE THREAD

**Issue by foxycode** [naja-js/naja#413]
# Feature Request

When Naja is dispatching AJAX requests, `ETag` is ignored and response is generated all the time. If Naja would send `If-None-Match` header with `ETag` from previous request as value, whole app could leverage one more cache level.

**Comment by jiripudil** [comment]
Hi, Naja builds on top of Fetch API and allows you to [configure its parameters](https://naja.js.org/#/dispatch?id=configuring-the-request), including the [cache mode](https://developer.mozilla.org/en-US/docs/Web/API/Request/cache). Beyond that, caching and sending the right headers are the responsibility of the browser, so if it does not work, it might be misconfigured
